### TODO: Add your integration tests here


### Get Tests
< {%
    request.variables.set("identifier", "g_garywoodfine_0001")
%}
GET {{host}}/{{websites_resource_name}}/{{identifier}}
accept: application/json
Content-Type: application/json

> ../../Asserts/Websites/Get/Should_be_200_Ok.js

###

